<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <!-- Generated via Iro -->
    <dict>
        <key>fileTypes</key>
        <array>
            <string>dit</string>
        </array>
        <key>name</key>
        <string>dit</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#main</string>
            </dict>
        </array>
        <key>scopeName</key>
        <string>source.dit</string>
        <key>uuid</key>
        <string></string>
        <key>repository</key>
        <dict>
            <key>main</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>(import|from|class|sig|func|return|throw|catch|try|pull|as|this)</string>
                        <key>name</key>
                        <string>keyword.dit</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(null|false|true)</string>
                        <key>name</key>
                        <string>constant.dit</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(Thing|Bool|Num|Str|listOf|JSON|Class|Lang|Instance|Dit)</string>
                        <key>name</key>
                        <string>support.dit</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(Python|JavaScript|Lua|print|getConfig|Parents|Priority|Make)</string>
                        <key>name</key>
                        <string>entity.dit</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(\b[A-z][A-z0-9_-]*)</string>
                        <key>name</key>
                        <string>variable.dit</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#numeric</string>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\{\|)</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#main__1</string>
                            </dict>
                        </array>
                        <key>end</key>
                        <string>(\|\})</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(&lt;\|)</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#main__2</string>
                            </dict>
                        </array>
                        <key>end</key>
                        <string>(\|&gt;)</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\(\|)</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#main__3</string>
                            </dict>
                        </array>
                        <key>end</key>
                        <string>(\|\))</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\&quot;)</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                        <key>contentName</key>
                        <string>text.dit</string>
                        <key>end</key>
                        <string>(\&quot;)</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(\&apos;)</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                        <key>contentName</key>
                        <string>text.dit</string>
                        <key>end</key>
                        <string>(\&apos;)</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.dit</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#multi_line_comment</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(//.*)</string>
                        <key>name</key>
                        <string>comment.dit</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(#.*)</string>
                        <key>name</key>
                        <string>comment.dit</string>
                    </dict>
                </array>
            </dict>
            <key>main__1</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#main</string>
                    </dict>
                </array>
            </dict>
            <key>main__2</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#main</string>
                    </dict>
                </array>
            </dict>
            <key>main__3</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#main</string>
                    </dict>
                </array>
            </dict>
            <key>main__4</key>
            <dict>
                <key>patterns</key>
                <array>
                </array>
            </dict>
            <key>main__5</key>
            <dict>
                <key>patterns</key>
                <array>
                </array>
            </dict>
            <key>multi_line_comment</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>(/\*)</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>comment.dit</string>
                            </dict>
                        </dict>
                        <key>contentName</key>
                        <string>comment.dit</string>
                        <key>end</key>
                        <string>(\*/)</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>comment.dit</string>
                            </dict>
                        </dict>
                    </dict>
                </array>
            </dict>
            <key>multi_line_comment__1</key>
            <dict>
                <key>patterns</key>
                <array>
                </array>
            </dict>
            <key>numeric</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>(\b\d+)</string>
                        <key>name</key>
                        <string>constant.numeric.dit</string>
                    </dict>
                </array>
            </dict>
        </dict>
    </dict>
</plist>
